### ISSUE TITLE
Error: Class 'Drupal\user\Entity\User' not found

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa01#17]
When running the `drush uli` command, I get the following error:

```console
vagrant@uiowa01:/var/www/uiowa01/docroot/sites/iowasuperfund$ drush @iowasuperfund.local uli
 [error]  Error: Class 'Drupal\user\Entity\User' not found in Drush\Commands\core\LoginCommands->login() (line 71 of /var/www/uiowa01/vendor/drush/drush/src/Commands/core/LoginCommands.php) #0 [internal function]: Drush\Commands\core\LoginCommands->login('', Array)
#1 /var/www/uiowa01/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
#2 /var/www/uiowa01/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#3 /var/www/uiowa01/vendor/consolidation/annotated-command/src/CommandProcessor.php(178): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#4 /var/www/uiowa01/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(302): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#5 /var/www/uiowa01/vendor/symfony/console/Command/Command.php(255): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/uiowa01/vendor/symfony/console/Application.php(987): Symfony\Component\Console\Command\Command->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/uiowa01/vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/uiowa01/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/uiowa01/vendor/drush/drush/src/Runtime/Runtime.php(118): Symfony\Component\Console\Application->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/uiowa01/vendor/drush/drush/src/Runtime/Runtime.php(49): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/uiowa01/vendor/drush/drush/drush.php(72): Drush\Runtime\Runtime->run(Array)
#12 /var/www/uiowa01/vendor/drush/drush/includes/preflight.inc(18): require('/var/www/uiowa0...')
#13 phar:///usr/local/bin/drush/bin/drush.php(141): drush_main()
#14 /usr/local/bin/drush(10): require('phar:///usr/loc...')
#15 {main}. 
```

This was not happening before sometime in the last week or two. The error means that I can't get a login link.

Some issues that might be related:
- https://github.com/drush-ops/drush/issues/2046
- https://github.com/drush-ops/drush/issues/3416
- https://drupal.stackexchange.com/questions/221683/class-drupal-user-entity-user-not-found-when-running-drush
- https://github.com/geerlingguy/drupal-vm/issues/1020
- https://www.drupal.org/project/drupal/issues/1944684

**Comment by pyrello** [comment]
This was an issue because there was not an entry in the docroot/sites/sites.php file. If this is the case, certain commands will fail and the site will not be able to accessed via its URL's.

**Comment by pyrello** [comment]
This issue cropped up for me again. It is happening to me on the feature_remove_lightning_components branch, but not on master. I tried it on a couple different sites, including @theming.local, which is our standard testing site.

**Comment by pyrello** [comment]
Hmm... after switching back to the feature branch from master, `drush uli` works again without issue.
