### ISSUE TITLE
Error when AC database already exists

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa01#44]
```
Client error: `POST https://cloud.acquia.com/api/applications/21a2a0ab-b4ed-4ecf-8bd4-9266c70f5ef1/databases` resulted in a `400 Bad Request` response:
{
    "error": "validation_failed",
    "message": {
        "name": "A database with that name already exists. Please c (truncated...)
PHP Fatal error:  Uncaught Error: Wrong parameters for Exception([string $message [, long $code [, Throwable $previous = NULL]]]) in /var/www/uiowa01/vendor/typhonius/acquia-php-sdk-v2/src/CloudApi/Connector.php:113
Stack trace:
#0 /var/www/uiowa01/vendor/typhonius/acquia-php-sdk-v2/src/CloudApi/Connector.php(113): Exception->__construct(Object(stdClass))
#1 /var/www/uiowa01/vendor/typhonius/acquia-php-sdk-v2/src/CloudApi/Connector.php(71): AcquiaCloudApi\CloudApi\Connector->processResponse(Object(GuzzleHttp\Psr7\Response))
#2 /var/www/uiowa01/vendor/typhonius/acquia-php-sdk-v2/src/CloudApi/Client.php(237): AcquiaCloudApi\CloudApi\Connector->request('post', '/applications/2...', Array, Array)
#3 /var/www/uiowa01/blt/src/Blt/Plugin/Commands/MultisiteCommands.php(238): AcquiaCloudApi\CloudApi\Client->databaseCreate('21a2a0ab-b4ed-4...', 'iywp_org')
#4 /var/www/uiowa01/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/ProcessResultHookDispatcher.php(46): Example\Blt\Plugin\Commands\MultisiteCommands->postMultisite(NULL in /var/www/uiowa01/vendor/typhonius/acquia-php-sdk-v2/src/CloudApi/Connector.php on line 113

Fatal error: Uncaught Error: Wrong parameters for Exception([string $message [, long $code [, Throwable $previous = NULL]]]) in /var/www/uiowa01/vendor/typhonius/acquia-php-sdk-v2/src/CloudApi/Connector.php:113
Stack trace:
#0 /var/www/uiowa01/vendor/typhonius/acquia-php-sdk-v2/src/CloudApi/Connector.php(113): Exception->__construct(Object(stdClass))
#1 /var/www/uiowa01/vendor/typhonius/acquia-php-sdk-v2/src/CloudApi/Connector.php(71): AcquiaCloudApi\CloudApi\Connector->processResponse(Object(GuzzleHttp\Psr7\Response))
#2 /var/www/uiowa01/vendor/typhonius/acquia-php-sdk-v2/src/CloudApi/Client.php(237): AcquiaCloudApi\CloudApi\Connector->request('post', '/applications/2...', Array, Array)
#3 /var/www/uiowa01/blt/src/Blt/Plugin/Commands/MultisiteCommands.php(238): AcquiaCloudApi\CloudApi\Client->databaseCreate('21a2a0ab-b4ed-4...', 'iywp_org')
#4 /var/www/uiowa01/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/ProcessResultHookDispatcher.php(46): Example\Blt\Plugin\Commands\MultisiteCommands->postMultisite(NULL in /var/www/uiowa01/vendor/typhonius/acquia-php-sdk-v2/src/CloudApi/Connector.php on line 113
```

**Comment by pyrello** [comment]
Targeted for #36.
